git ignore

diff --git a/achat/Jenkinsfile b/achat/Jenkinsfile
--- a/achat/Jenkinsfile
+++ b/achat/Jenkinsfile
@@ -49,8 +49,7 @@ pipeline {
                         --disableCentral ^
                         --noupdate ^
                         --nvdMaxRetryCount 2 ^
-                        --exclude image.tar ^
-                        --exclude trivy-cache
+                        --exclude image.tar
                         """
                     }
                 }
@@ -125,9 +124,11 @@ pipeline {
         stage('Run Application & Stack') {
             steps {
                 dir('achat') {
-                    bat 'docker compose down -v --remove-orphans || exit 0'
-                    bat 'docker compose up -d'
-                    bat 'docker ps'
+                    bat '''
+                    docker compose down -v --remove-orphans || exit 0
+                    docker compose --env-file .env up -d
+                    docker ps
+                    '''
                 }
             }
         }
@@ -179,7 +180,7 @@ pipeline {
         }
 
         failure {
-            echo '❌ Pipeline FAILED (build / security / scans)'
+            echo '❌ Pipeline FAILED'
         }
 
         always {
